services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"  
    network_mode: bridge 
    volumes:
      - .:/client
      - /client/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0 
      - PORT=5173
    stdin_open: true
    tty: true